import type { PostMeta } from "./posts";

const posts: PostMeta[] = [
  {
    title: "Best AI Video Generators for Content Creators in 2025: Tested & Ranked",
    description:
      "We tested Runway, Pika, Kling, and Sora side-by-side so you can pick the right AI video generator for your YouTube channel or faceless content workflow.",
    slug: "best-ai-video-generators-2025",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-01",
    updated: "2025-06-10",
    keywords: [
      "best AI video generator 2025",
      "Runway vs Pika",
      "AI video tools for YouTube",
      "Kling AI review",
      "Sora review for creators",
    ],
    affiliateDisclosure: true,
    rating: 4.2,
  },
  {
    title: "Best AI Voice Generators for YouTube in 2025: ElevenLabs vs Murf vs Play.ht Reviewed",
    description:
      "We compared the top AI text-to-speech tools for YouTube creators — ElevenLabs, Murf, Play.ht, and Descript — on voice quality, cloning accuracy, price, and workflow.",
    slug: "best-ai-voice-generators-youtube",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-05-20",
    updated: "2025-06-08",
    keywords: [
      "best AI voice generator YouTube",
      "ElevenLabs review",
      "Murf AI review",
      "AI text to speech for content creators",
      "voice cloning for YouTube",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "Best AI Thumbnail Generators for YouTube (2025): Midjourney vs Adobe Firefly vs Canva AI",
    description:
      "We tested the top AI image generators specifically for YouTube thumbnails — comparing click-through rates, ease of use, text handling, and cost per thumbnail.",
    slug: "best-ai-thumbnail-tools",
    category: "AI Images & Thumbnails",
    categorySlug: "ai-images-thumbnails",
    date: "2025-05-10",
    updated: "2025-06-05",
    keywords: [
      "AI thumbnail generator YouTube",
      "Midjourney for YouTubers",
      "Adobe Firefly review",
      "Canva AI thumbnails",
      "best AI image tool for YouTube",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "Best AI Scriptwriting Tools for YouTube in 2025: Claude vs ChatGPT vs Jasper",
    description:
      "We tested 5 AI scriptwriting tools on real YouTube scripts — comparing hook quality, spoken-language naturalness, and price. Includes a free copy-paste prompt template.",
    slug: "best-ai-script-writers",
    category: "AI Scriptwriting & Text",
    categorySlug: "ai-scriptwriting-text",
    date: "2025-05-05",
    updated: "2025-06-12",
    keywords: [
      "best AI scriptwriting tool YouTube",
      "Claude vs ChatGPT for YouTube scripts",
      "Jasper YouTube script review",
      "AI script generator for content creators",
      "YouTube script AI 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.4,
  },
  {
    title: "Best AI Workflow & Automation Tools for YouTube Creators (2025)",
    description:
      "How to automate your YouTube channel with Make, Opus Clip, TubeBuddy, and Zapier — saving 10+ hours a week on publishing, repurposing, and research.",
    slug: "best-ai-automation-tools-youtube",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-04-28",
    updated: "2025-06-11",
    keywords: [
      "YouTube automation tools 2025",
      "Make Integromat YouTube",
      "Opus Clip review",
      "TubeBuddy review",
      "automate YouTube channel AI",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "ElevenLabs Review 2025: The Best AI Voice Generator for YouTube Creators?",
    description:
      "In-depth ElevenLabs review after 6 months of real use — voice cloning quality, pricing breakdown, API setup, and honest comparison vs Murf and Play.ht.",
    slug: "elevenlabs-review",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-06-10",
    updated: "2025-06-13",
    keywords: [
      "ElevenLabs review 2025",
      "ElevenLabs voice cloning",
      "best AI voice generator YouTube",
      "ElevenLabs pricing",
      "ElevenLabs vs Murf",
    ],
    affiliateDisclosure: true,
    rating: 4.8,
  },
  {
    title: "Kling AI Review 2025: The Best Budget AI Video Generator?",
    description:
      "Kling AI review after 2 months of production use on a faceless YouTube channel — comparing video quality, physics simulation, pricing, and API vs Runway and Pika.",
    slug: "kling-ai-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-08",
    updated: "2025-06-13",
    keywords: [
      "Kling AI review 2025",
      "Kling vs Runway",
      "best AI video generator budget",
      "Kling AI faceless YouTube",
      "Kling 1.6 review",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "Midjourney for YouTube Thumbnails: The Complete Prompt Guide (2025)",
    description:
      "Exact Midjourney prompts and Canva workflow for creating high-CTR YouTube thumbnails. Includes niche-specific templates for finance, tech, motivation, and more.",
    slug: "midjourney-youtube-thumbnail-guide",
    category: "AI Images & Thumbnails",
    categorySlug: "ai-images-thumbnails",
    date: "2025-06-05",
    updated: "2025-06-12",
    keywords: [
      "Midjourney YouTube thumbnails",
      "Midjourney prompt guide thumbnails",
      "how to make YouTube thumbnails AI",
      "Midjourney Canva workflow",
      "AI thumbnail design 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.7,
  },
  {
    title: "How to Start a Faceless YouTube Channel with AI Tools in 2025",
    description:
      "The complete step-by-step guide to launching a faceless YouTube channel using AI — covering niche selection, scripting, voiceover, editing, thumbnails, and SEO.",
    slug: "how-to-start-faceless-youtube-channel-ai",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-03",
    updated: "2025-06-13",
    keywords: [
      "how to start faceless YouTube channel",
      "faceless YouTube channel AI tools",
      "faceless YouTube channel 2025",
      "AI faceless channel guide",
      "start YouTube channel no face",
    ],
    affiliateDisclosure: true,
    rating: 4.6,
  },
  {
    title: "Opus Clip Review 2025: Is AI-Powered Repurposing Worth It?",
    description:
      "We used Opus Clip for 90 days across two YouTube channels — clip selection quality, virality scores, auto-reframe accuracy, and whether the Pro plan is worth $29/month.",
    slug: "opus-clip-review",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-05-28",
    updated: "2025-06-11",
    keywords: [
      "Opus Clip review 2025",
      "Opus Clip vs manual editing",
      "AI YouTube Shorts tool",
      "best repurposing tool YouTube",
      "Opus Clip pricing",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "TubeBuddy Review 2025: Still Worth It for Growing YouTube Channels?",
    description:
      "Honest TubeBuddy review after 4 months across three channels — Keyword Explorer accuracy, A/B thumbnail testing results, bulk processing, and whether Pro is worth $4.99/month.",
    slug: "tubebuddy-review",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-05-15",
    updated: "2025-06-10",
    keywords: [
      "TubeBuddy review 2025",
      "TubeBuddy vs vidIQ",
      "TubeBuddy keyword explorer",
      "best YouTube SEO tool",
      "TubeBuddy Pro worth it",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
];

export default posts;
