import type { PostMeta } from "./posts";

const posts: PostMeta[] = [
  {
    title: "Best AI Video Generators for Content Creators in 2025: Tested & Ranked",
    description:
      "We tested Runway, Pika, Kling, and Sora side-by-side so you can pick the right AI video generator for your YouTube channel or faceless content workflow.",
    slug: "best-ai-video-generators-2025",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-01",
    updated: "2025-06-10",
    keywords: [
      "best AI video generator 2025",
      "Runway vs Pika",
      "AI video tools for YouTube",
      "Kling AI review",
      "Sora review for creators",
    ],
    affiliateDisclosure: true,
    rating: 4.2,
  },
  {
    title: "Best AI Voice Generators for YouTube in 2025: ElevenLabs vs Murf vs Play.ht Reviewed",
    description:
      "We compared the top AI text-to-speech tools for YouTube creators — ElevenLabs, Murf, Play.ht, and Descript — on voice quality, cloning accuracy, price, and workflow.",
    slug: "best-ai-voice-generators-youtube",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-05-20",
    updated: "2025-06-08",
    keywords: [
      "best AI voice generator YouTube",
      "ElevenLabs review",
      "Murf AI review",
      "AI text to speech for content creators",
      "voice cloning for YouTube",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "Best AI Thumbnail Generators for YouTube (2025): Midjourney vs Adobe Firefly vs Canva AI",
    description:
      "We tested the top AI image generators specifically for YouTube thumbnails — comparing click-through rates, ease of use, text handling, and cost per thumbnail.",
    slug: "best-ai-thumbnail-tools",
    category: "AI Images & Thumbnails",
    categorySlug: "ai-images-thumbnails",
    date: "2025-05-10",
    updated: "2025-06-05",
    keywords: [
      "AI thumbnail generator YouTube",
      "Midjourney for YouTubers",
      "Adobe Firefly review",
      "Canva AI thumbnails",
      "best AI image tool for YouTube",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "Best AI Scriptwriting Tools for YouTube in 2025: Claude vs ChatGPT vs Jasper",
    description:
      "We tested 5 AI scriptwriting tools on real YouTube scripts — comparing hook quality, spoken-language naturalness, and price. Includes a free copy-paste prompt template.",
    slug: "best-ai-script-writers",
    category: "AI Scriptwriting & Text",
    categorySlug: "ai-scriptwriting-text",
    date: "2025-05-05",
    updated: "2025-06-12",
    keywords: [
      "best AI scriptwriting tool YouTube",
      "Claude vs ChatGPT for YouTube scripts",
      "Jasper YouTube script review",
      "AI script generator for content creators",
      "YouTube script AI 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.4,
  },
  {
    title: "Best AI Workflow & Automation Tools for YouTube Creators (2025)",
    description:
      "How to automate your YouTube channel with Make, Opus Clip, TubeBuddy, and Zapier — saving 10+ hours a week on publishing, repurposing, and research.",
    slug: "best-ai-automation-tools-youtube",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-04-28",
    updated: "2025-06-11",
    keywords: [
      "YouTube automation tools 2025",
      "Make Integromat YouTube",
      "Opus Clip review",
      "TubeBuddy review",
      "automate YouTube channel AI",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "ElevenLabs Review 2025: The Best AI Voice Generator for YouTube Creators?",
    description:
      "In-depth ElevenLabs review after 6 months of real use — voice cloning quality, pricing breakdown, API setup, and honest comparison vs Murf and Play.ht.",
    slug: "elevenlabs-review",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-06-10",
    updated: "2025-06-13",
    keywords: [
      "ElevenLabs review 2025",
      "ElevenLabs voice cloning",
      "best AI voice generator YouTube",
      "ElevenLabs pricing",
      "ElevenLabs vs Murf",
    ],
    affiliateDisclosure: true,
    rating: 4.8,
  },
  {
    title: "Kling AI Review 2025: The Best Budget AI Video Generator?",
    description:
      "Kling AI review after 2 months of production use on a faceless YouTube channel — comparing video quality, physics simulation, pricing, and API vs Runway and Pika.",
    slug: "kling-ai-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-08",
    updated: "2025-06-13",
    keywords: [
      "Kling AI review 2025",
      "Kling vs Runway",
      "best AI video generator budget",
      "Kling AI faceless YouTube",
      "Kling 1.6 review",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "Midjourney for YouTube Thumbnails: The Complete Prompt Guide (2025)",
    description:
      "Exact Midjourney prompts and Canva workflow for creating high-CTR YouTube thumbnails. Includes niche-specific templates for finance, tech, motivation, and more.",
    slug: "midjourney-youtube-thumbnail-guide",
    category: "AI Images & Thumbnails",
    categorySlug: "ai-images-thumbnails",
    date: "2025-06-05",
    updated: "2025-06-12",
    keywords: [
      "Midjourney YouTube thumbnails",
      "Midjourney prompt guide thumbnails",
      "how to make YouTube thumbnails AI",
      "Midjourney Canva workflow",
      "AI thumbnail design 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.7,
  },
  {
    title: "How to Start a Faceless YouTube Channel with AI Tools in 2025",
    description:
      "The complete step-by-step guide to launching a faceless YouTube channel using AI — covering niche selection, scripting, voiceover, editing, thumbnails, and SEO.",
    slug: "how-to-start-faceless-youtube-channel-ai",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-03",
    updated: "2025-06-13",
    keywords: [
      "how to start faceless YouTube channel",
      "faceless YouTube channel AI tools",
      "faceless YouTube channel 2025",
      "AI faceless channel guide",
      "start YouTube channel no face",
    ],
    affiliateDisclosure: true,
    rating: 4.6,
  },
  {
    title: "Opus Clip Review 2025: Is AI-Powered Repurposing Worth It?",
    description:
      "We used Opus Clip for 90 days across two YouTube channels — clip selection quality, virality scores, auto-reframe accuracy, and whether the Pro plan is worth $29/month.",
    slug: "opus-clip-review",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-05-28",
    updated: "2025-06-11",
    keywords: [
      "Opus Clip review 2025",
      "Opus Clip vs manual editing",
      "AI YouTube Shorts tool",
      "best repurposing tool YouTube",
      "Opus Clip pricing",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "TubeBuddy Review 2025: Still Worth It for Growing YouTube Channels?",
    description:
      "Honest TubeBuddy review after 4 months across three channels — Keyword Explorer accuracy, A/B thumbnail testing results, bulk processing, and whether Pro is worth $4.99/month.",
    slug: "tubebuddy-review",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-05-15",
    updated: "2025-06-10",
    keywords: [
      "TubeBuddy review 2025",
      "TubeBuddy vs vidIQ",
      "TubeBuddy keyword explorer",
      "best YouTube SEO tool",
      "TubeBuddy Pro worth it",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "HeyGen Review 2025: The Best AI Avatar Tool for YouTube Creators?",
    description:
      "In-depth HeyGen review after 90 days of production use — avatar realism, translation quality, credit system gotchas, and whether the $89/month Business plan is worth it for faceless YouTube channels.",
    slug: "heygen-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-13",
    updated: "2025-06-14",
    keywords: [
      "HeyGen review 2025",
      "HeyGen AI avatar",
      "best AI avatar tool YouTube",
      "HeyGen vs Synthesia",
      "AI presenter video tool",
    ],
    affiliateDisclosure: true,
    rating: 4.6,
  },
  {
    title: "Pictory AI Review 2025: Turn Blog Posts into YouTube Videos Automatically",
    description:
      "Honest Pictory AI review for faceless channel creators — blog-to-video workflow, stock footage quality, voiceover options, and whether the $39/month Professional plan delivers real time savings.",
    slug: "pictory-ai-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-12",
    updated: "2025-06-14",
    keywords: [
      "Pictory AI review 2025",
      "Pictory blog to video",
      "AI video maker for YouTube",
      "faceless YouTube channel tools",
      "Pictory vs InVideo",
    ],
    affiliateDisclosure: true,
    rating: 4.2,
  },
  {
    title: "Best Free AI Tools for YouTube Creators in 2025 (Tested Workflow)",
    description:
      "The complete free AI tool stack for YouTube creators — what each free tier actually includes, which tools hit their limits first, and how to build a professional faceless channel workflow at $0/month.",
    slug: "best-free-ai-tools-youtube",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-11",
    updated: "2025-06-14",
    keywords: [
      "best free AI tools for YouTube",
      "free AI tools content creators",
      "AI YouTube tools free",
      "free faceless YouTube tools",
      "free AI video tools 2025",
    ],
    affiliateDisclosure: false,
  },
  {
    title: "How to Make YouTube Shorts with AI: Complete 2025 Guide",
    description:
      "Step-by-step guide to building a YouTube Shorts workflow with AI — from script and voiceover to captions and publishing. Covers both original AI Shorts and repurposing long-form content with Opus Clip.",
    slug: "how-to-make-youtube-shorts-with-ai",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-10",
    updated: "2025-06-14",
    keywords: [
      "how to make YouTube Shorts with AI",
      "AI YouTube Shorts workflow",
      "YouTube Shorts AI tools",
      "faceless YouTube Shorts",
      "make Shorts faster AI",
    ],
    affiliateDisclosure: false,
  },
  {
    title: "InVideo AI Review 2025: Best All-in-One AI Video Maker for YouTube?",
    description:
      "Full InVideo AI review after 3 months of production use — script generation quality, footage matching, voiceover options, credit system gotchas, and whether $25-$60/month is worth it for faceless channels.",
    slug: "invideo-ai-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-14",
    updated: "2025-06-14",
    keywords: [
      "InVideo AI review 2025",
      "InVideo AI faceless YouTube",
      "best AI video maker YouTube",
      "InVideo vs Pictory",
      "InVideo AI pricing",
    ],
    affiliateDisclosure: true,
    rating: 4.3,
  },
  {
    title: "Murf AI Review 2025: Professional Voiceover Studio for YouTube Creators",
    description:
      "Honest Murf AI review after 4 months of production use — voice quality vs ElevenLabs, built-in video studio, per-word emphasis control, and whether the $29/month Creator plan justifies the premium.",
    slug: "murf-ai-review",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-06-14",
    updated: "2025-06-14",
    keywords: [
      "Murf AI review 2025",
      "Murf AI vs ElevenLabs",
      "best AI voiceover YouTube",
      "Murf AI pricing",
      "AI voice generator YouTube",
    ],
    affiliateDisclosure: true,
    rating: 4.4,
  },
  {
    title: "Claude vs ChatGPT for YouTube Scripts: Which AI Writes Better Content?",
    description:
      "40-session comparison of Claude and ChatGPT for YouTube scriptwriting across 5 niches — hook quality, script length, tone, accuracy, and which tool wins for your specific content format.",
    slug: "claude-vs-chatgpt-youtube-scripts",
    category: "AI Scriptwriting & Text",
    categorySlug: "ai-scriptwriting-text",
    date: "2025-06-14",
    updated: "2025-06-14",
    keywords: [
      "Claude vs ChatGPT YouTube scripts",
      "best AI for YouTube scriptwriting",
      "Claude YouTube script",
      "ChatGPT YouTube content",
      "AI scriptwriting comparison 2025",
    ],
    affiliateDisclosure: false,
  },
  {
    title: "vidIQ Review 2025: Is It Better Than TubeBuddy for YouTube SEO?",
    description:
      "In-depth vidIQ review across 3 channels for 4 months — keyword research accuracy, daily video ideas, competitor tracking, mobile app, and the honest TubeBuddy comparison every creator needs to read.",
    slug: "vidiq-review",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-14",
    updated: "2025-06-14",
    keywords: [
      "vidIQ review 2025",
      "vidIQ vs TubeBuddy",
      "best YouTube SEO tool",
      "vidIQ Pro worth it",
      "YouTube keyword research tool",
    ],
    affiliateDisclosure: true,
    rating: 4.2,
  },
  {
    title: "Runway ML Review 2025: The Highest Quality AI Video Generator?",
    description:
      "Deep-dive Runway Gen-3 Alpha review — output quality vs Kling AI, Motion Brush, Act One, credit system, and when the $35/month Pro plan is worth the premium over cheaper alternatives.",
    slug: "runway-ml-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-14",
    updated: "2025-06-14",
    keywords: [
      "Runway ML review 2025",
      "Runway Gen-3 Alpha review",
      "Runway vs Kling AI",
      "best AI video generator quality",
      "Runway AI pricing",
    ],
    affiliateDisclosure: true,
    rating: 4.6,
  },
  {
    title: "HeyGen vs Synthesia 2025: Which AI Avatar Tool Is Better for YouTube?",
    description:
      "90-day head-to-head comparison of HeyGen and Synthesia across three channels — avatar realism, video translation, custom avatar setup, pricing, and which tool wins for YouTube creators vs corporate use.",
    slug: "heygen-vs-synthesia",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-15",
    updated: "2025-06-15",
    keywords: [
      "HeyGen vs Synthesia 2025",
      "HeyGen vs Synthesia for YouTube",
      "best AI avatar tool YouTube",
      "HeyGen review 2025",
      "Synthesia review 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.5,
  },
  {
    title: "ElevenLabs vs Murf AI 2025: Which Voice Generator Is Better for YouTube?",
    description:
      "6-month comparison of ElevenLabs and Murf AI for YouTube voiceovers — voice realism, cloning, pronunciation control, pricing, and which tool wins for content creators building faceless channels.",
    slug: "elevenlabs-vs-murf",
    category: "AI Voice & Text-to-Speech",
    categorySlug: "ai-voice-tts",
    date: "2025-06-15",
    updated: "2025-06-15",
    keywords: [
      "ElevenLabs vs Murf AI 2025",
      "ElevenLabs vs Murf for YouTube",
      "best AI voice generator YouTube 2025",
      "ElevenLabs review vs Murf",
      "AI voiceover comparison 2025",
    ],
    affiliateDisclosure: true,
    rating: 4.6,
  },
  {
    title: "Best AI Prompts for YouTube Script Writing (Copy-Paste Templates 2025)",
    description:
      "The exact AI prompts I use to write YouTube scripts across 6 channels — hook generators, full-script templates, Shorts prompts, SEO descriptions, and a 10-rule system for better AI output every time.",
    slug: "best-ai-prompts-youtube-scripts",
    category: "AI Scriptwriting & Text",
    categorySlug: "ai-scriptwriting-text",
    date: "2025-06-15",
    updated: "2025-06-15",
    keywords: [
      "AI prompts for YouTube scripts",
      "ChatGPT prompts YouTube scriptwriting",
      "best prompts YouTube video scripts",
      "AI script writing templates YouTube",
      "ChatGPT YouTube script prompt 2025",
    ],
    affiliateDisclosure: false,
  },
  {
    title: "How to Use ChatGPT to Grow Your YouTube Channel in 2025 (Full Workflow)",
    description:
      "The complete ChatGPT workflow for YouTube growth — niche research, title optimization, SEO descriptions, comment replies, content calendars, and a weekly system that saves 8-12 hours per week.",
    slug: "chatgpt-youtube-channel-growth",
    category: "AI Scriptwriting & Text",
    categorySlug: "ai-scriptwriting-text",
    date: "2025-06-15",
    updated: "2025-06-15",
    keywords: [
      "how to use ChatGPT for YouTube",
      "ChatGPT YouTube channel growth",
      "ChatGPT YouTube strategy 2025",
      "grow YouTube channel with AI",
      "ChatGPT YouTube workflow",
    ],
    affiliateDisclosure: false,
  },
  {
    title: "CapCut AI Review 2025: The Best Free AI Video Editor for YouTube?",
    description:
      "Honest CapCut AI review after 4 months across two channels — auto-captions, script-to-video, AI avatars, auto-reframe, the watermark problem, and whether the $9.99 Pro plan is worth it.",
    slug: "capcut-ai-review",
    category: "AI Video Tools",
    categorySlug: "ai-video-tools",
    date: "2025-06-30",
    updated: "2025-06-30",
    keywords: [
      "CapCut AI review 2025",
      "CapCut AI features YouTube",
      "best free AI video editor YouTube",
      "CapCut Pro worth it",
      "CapCut vs DaVinci Resolve",
    ],
    affiliateDisclosure: false,
    rating: 4.3,
  },
  {
    title: "Best AI Tools for Faceless YouTube Channels 2025: The Complete Stack",
    description:
      "The exact AI tool stack used across three monetized faceless channels — research, scripting, voiceover, video generation, editing, and thumbnails. Includes free, $50/month, and $150/month setups.",
    slug: "best-ai-tools-faceless-youtube",
    category: "AI Workflows & Automation",
    categorySlug: "ai-workflows-automation",
    date: "2025-06-30",
    updated: "2025-06-30",
    keywords: [
      "best AI tools for faceless YouTube channels",
      "faceless YouTube channel AI stack 2025",
      "AI tools faceless YouTube 2025",
      "best tools faceless channel",
      "faceless YouTube channel tools free",
    ],
    affiliateDisclosure: false,
  },
];

export default posts;
